# Database
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dev
    username: dev
    password: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      setting:
        web-allow-others: true